# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light1', models.BooleanField()),
                ('light2', models.BooleanField()),
                ('toaster', models.BooleanField()),
                ('nuclearDefenseSystem', models.BooleanField()),
            ],
        ),
    ]
